jamatulmsl/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('', views.index, name='index'),
    path('addResume', views.savepersondetails.as_view(), name = 'addResume'),
    path('signup', views.signupPage, name='signupPage'),
    path('login', views.loginPage, name='loginPage'),
    path('logout', views.logoutPage, name='logoutPage'),
    path('listResume', views.listResume.as_view(), name='listResume'),
    path('viewResume', views.viewResume.as_view(), name='viewResume'),
    path('exportdata', views.exportdata.as_view(), name='exportdata'),
    path('exporttoexcel', views.exporttoexcel.as_view(), name='exporttoexcel'),
    path('updatedetails/<int:phoneno>/', views.updatedetails.as_view(), name='updatedetails')
] 

jamatulmuslimeen/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from jamatulmsl import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('jamatulmsl.urls')),
    path('<int:Contact_number>/', views.viewResume.as_view(), name="viewResume"),
    path('listResume/', views.listResume.as_view(), name="listResume"),

] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jamatulmsl/models.py
from functools import partial
import os
from django.db import models
from django.contrib.auth.models import User


def aadharcard(instance, Aadhar_card, thumbnail=False):
    name, ext = os.path.splitext(Aadhar_card)
    path = f'Aadhar_card/{instance.Contact_number}/{name if thumbnail else ""}{ext}'
    n = 1
    while os.path.exists(path):
        path = f'{instance.Contact_number}/-{n}{ext}'
        n += 1
    return path

def deathcertificate(instance, Death_certificate, thumbnail=False):
    name, ext = os.path.splitext(Death_certificate)
    path = f'Death_certificate/{instance.Contact_number}/{name if thumbnail else ""}{ext}'
    n = 1
    while os.path.exists(path):
        path = f'{instance.Contact_number}/-{n}{ext}'
        n += 1
    return path

def otherfile(instance, Other_file, thumbnail=False):
    name, ext = os.path.splitext(Other_file)
    path = f'Other_file/{instance.Contact_number}/{name if thumbnail else ""}{ext}'
    n = 1
    while os.path.exists(path):
        path = f'{instance.Contact_number}/-{n}{ext}'
        n += 1
    return path

class metainformation(models.Model):

    USERID              = models.CharField(max_length=50, blank=False)
    Applicant_name      = models.CharField(max_length=50, blank=False)
    Deceased_name       = models.CharField(max_length=50, blank=False)
    Deceased_age        = models.CharField(max_length=3, null=True)
    Gender              = models.CharField(max_length=50, blank=False)
    Contact_number      = models.CharField(max_length=10, blank=False)
    Address             = models.CharField(max_length=255, blank=False)
    Deceased_address    = models.CharField(max_length=255, blank=False)
    Date                = models.DateField()
    Date_of_death       = models.DateField()
    time_of_death       = models.TimeField()
    Cause_of_death      = models.CharField(max_length=255, blank=False)
    Relationship        = models.CharField(max_length=50, blank=False)
    Form_number         = models.IntegerField()
    Amount              = models.IntegerField()
    Aadhar_card         = models.FileField(upload_to =partial(aadharcard, thumbnail=True), blank=True, null=True, help_text="Browse a photo")
    Death_certificate   = models.FileField(upload_to =partial(deathcertificate, thumbnail=True), blank=True, null=True, help_text="Browse a photo")
    Other_file          = models.FileField(upload_to =partial(otherfile, thumbnail=True), blank=True, null=True, help_text="Browse a photo")

    def __str__(self):
        return self.Applicant_name

    class Meta :
        db_table = 'Person_Information'

class contactdetails(models.Model):
    name = models.CharField(max_length=60)
    email = models.EmailField()
    phoneno = models.CharField(max_length=12)
    msg = models.TextField()

    def __str__(self):
        return self.name
    
    class Meta :
        db_table = 'Contact_Us'

jamatulmsl/views.py
from asyncio import log
from collections import OrderedDict
import datetime
from django.shortcuts import render
from rest_framework.response import Response
from rest_framework.views import APIView
from .models import metainformation
from .serializers import metainfoserializer
from rest_framework import status
from django.shortcuts import render, HttpResponse, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from rest_framework.renderers import TemplateHTMLRenderer
from django.core.exceptions import ObjectDoesNotExist
from io import BytesIO
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
import csv


def render_to_pdf(template_src, context_dict={}):
    template = get_template(template_src)
    html  = template.render(context_dict)
    result = BytesIO()
    pdf = pisa.pisaDocument(BytesIO(html.encode("utf-8")), result)
    if not pdf.err:
        return HttpResponse(result.getvalue(), content_type='application/pdf')
    return None

# from django.template import loader
#  template = loader.get_template('template.html')


def index(request):

    return render(request, 'index.html')


def signupPage(request):

    if request.method == "POST":
        uname=request.POST.get("Username")
        fname=request.POST.get("Fname")
        lname=request.POST.get("Lname")
        email=request.POST.get("Emailid")
        pass1=request.POST.get("Password")
        pass2=request.POST.get("confirmPassword")

        if pass1 != pass2:
            messages.error(request, "Password doesn't match!")
            return redirect('signup')

        try:
            if User.objects.get(username = uname):
                messages.warning(request, "Username is already taken!")
                return redirect('signup')

        except Exception as identifier:
            pass

        try:
            if User.objects.get(email = email):
                messages.warning(request, "Email ID is already registered!")
                return redirect('signup')

        except Exception as identifier:
            pass

        myuser = User.objects.create_user(uname, email, pass1)
        myuser.first_name = fname
        myuser.last_name = lname
        myuser.save()

        messages.success(request, "SignUp Successful!")
        return render(request, 'login.html')

    return render(request, 'signup.html')

def loginPage(request):

    if request.method == "POST":
        uname=request.POST.get("Username")
        password=request.POST.get("Password")

        myuser = authenticate(username=uname, password=password)

        if myuser is not None:
            login(request, myuser)
            messages.success(request, "Login Successful!")
            return redirect('/')

        else:
            messages.error(request, "Invalid Credentials!")
            return redirect('/login')

    return render(request, 'login.html')


class savepersondetails(APIView):
    
    renderer_classes = [TemplateHTMLRenderer]

    def get(self, request):

        idcount = metainformation.objects.all()
        idlst = []
        for i in  idcount.values_list():
            idlst.append(i[0])
        if len(idlst) == 0:
            latestindex = '0'
        else:
            latestindex = idlst[-1] + 1

        condata = {
            'ids' : str(latestindex),
        }
        print(condata)

        return render(request, 'registrationform.html', {'context': condata['ids'] })
    
    def post(self, request):

        upfiles = request.FILES.get('Aadhar_card', False)
        upfiles1 = request.FILES.get('Death_certificate', False)
        upfiles2 = request.FILES.get('Other_file', False)


        serializer = metainfoserializer(data=request.data)
        if serializer.is_valid():


            if metainformation.objects.filter(Contact_number=request.data.get('Contact_number')).exists():
                return Response('Contact Number Already Exist')
            elif metainformation.objects.filter(Form_number=request.data.get('Form_number')).exists():
                return Response('Form Number Already Exist')


            metainformation.objects.get_or_create(
                                                USERID=request.user.username,
                                                Applicant_name=request.data.get('Applicant_name'),
                                                Deceased_name=request.data.get('Deceased_name'),
                                                Deceased_age=request.data.get('Deceased_age'),
                                                Gender=request.data.get('Gender'),
                                                Contact_number=request.data.get('Contact_number'),
                                                Address=request.data.get('Address'),
                                                Deceased_address=request.data.get('Deceased_address'),
                                                Date=request.data.get('Date'),
                                                Date_of_death=request.data.get('Date_of_death'),
                                                time_of_death=request.data.get('time_of_death'),
                                                Cause_of_death=request.data.get('Cause_of_death'),
                                                Relationship=request.data.get('Relationship'),
                                                Form_number=request.data.get('Form_number'),
                                                Aadhar_card=upfiles,
                                                Death_certificate=upfiles1,
                                                Other_file=upfiles2,
                                                Amount=request.data.get('Amount'))

            getdata = metainformation.objects.filter(Contact_number=request.data.get('Contact_number'))
            serialsdata = metainfoserializer(getdata, many=True)

            messages.success(request, "Your Applicant has been successfully added!")
            
            idcount = metainformation.objects.all()
            idlst = []
            for i in  idcount.values_list():
                idlst.append(i[0])
            latestindex = idlst[-1] + 1

            condata = {
                'ids' : str(latestindex),
            }
            
            return render(request, 'registrationform.html', {'context': condata['ids'] })
        messages.success(request, "Invalid Entry")
        return Response(serializer.error_messages,status=400, template_name='registrationform.html')


def logoutPage(request):
    logout(request)
    messages.success(request, 'Logout Successful!')
    return redirect('index')





class listResume(APIView):

    def get(self, request):

        current_user = request.user.username
        userid = metainformation.USERID

        if metainformation.objects.filter(USERID = current_user).exists():
            profile=metainformation.objects.filter(USERID = current_user)
            return render(request, "listResume.html", {'profile':profile})
        return render(request, 'listResume.html', status=status.HTTP_200_OK)

    def post(self, request):
        current_user = request.user.username
        current_user = request.data.get('Contact_number')
        userid = metainformation.USERID

        if metainformation.objects.filter(userid = current_user).exists():
            profile=metainformation.objects.filter(userid = current_user)
            return render(request, "listResume.html", {'profile':profile})   
        return render(request, "listResume.html", status=status.HTTP_202_ACCEPTED)






class viewResume(APIView):

    def post(self, request):
        try:
            contact = request.POST['Contact_number']
            user_profile = metainformation.objects.get(Contact_number=contact)
            template = get_template('burial.html')
            if  'button1' in request.POST:
                context ={
                     'user_profile':user_profile
                }
                html = template.render(context)
                # return render_to_pdf("burial.html", context)
                return render(request, "burial.html", {'user_profile':user_profile}, status=status.HTTP_202_ACCEPTED)
            if  'button2' in request.POST:
                return render(request, "planepdf.html", {'user_profile':user_profile}, status=status.HTTP_202_ACCEPTED)
            if  'button5' in request.POST:
                print(user_profile.Gender)
                if user_profile.Gender == 'male':
                    ini = 'Mr.'
                    pro = 'He'
                else:
                    ini = 'Ms.'
                    pro = 'She'
                return render(request, "burialc.html", {'user_profile':user_profile, 'ini': ini, 'pro':pro}, status=status.HTTP_202_ACCEPTED)
        except ObjectDoesNotExist:
            messages.error(request, 'Invalid Number OR Number Does Not Exist')
            return redirect('listResume')
        # try:
        #     contact = request.POST['Contact_number']
        #     user_profile = metainformation.objects.get(Contact_number=contact)
        #     template = get_template('burial.html')
        #     if  'button1' in request.POST:
        #         context ={
        #              'user_profile':user_profile
        #         }
        #         html = template.render(context)
        #         pdf = render_to_pdf('burial.html' ,context)
        #         if pdf:
        #             response = HttpResponse(pdf, content_type='application/pdf')
        #             filename = "Form C_%s.pdf" %("contact")
        #             content = "inline; filename='%s'" %(filename)
        #             download = request.GET.get("download")
        #             if download:
        #                 content = "attachment; filename='%s'" %(filename)

jamatulmsl/templates/editapplicant.html
{% extends 'base.html' %}

<!-- changing title of page -->

{% block title %}
Registration Form
{% endblock title %}

{% block body %}

<!-- creating container for adding details -->
<style>

    
    .container {
    width: 100%;
    padding-right: 30px;
    padding-left: 15px;
    margin-right: auto;
    margin-left: auto;
}
</style>
<div class="container">
    <div class="row pt-2 mb-3">
        <div class="text-center col-md-6"></div>
        <div class="col-md-12 mt-3 mb-3 ml-2 mr-2 my-auto border border-dark border-2 rounded-3">
            <h3 class="text-center mb-3 mt-3"></h3>

        {% for message in messages %}
        <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
          {{message}}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}

            <!-- creating form for adding resume details -->
            {% for userdata in user_datas %}
            <form action="/updatedetails/{{userdata.Contact_number}}/" method="post" enctype="multipart/form-data">{% csrf_token %}
                
                <label for="userid" class="form-label">User ID*</label>
                <div class="form-group">
                    <input type="text" class="form-control mb-3" id="USERID" name="USERID" value="{{userdata.USERID}}" readonly>
                </div>
                <label for="fno" class="form-label">Form Number*</label>
                <div class="form-group">
                    <input type="text" class="form-control mb-3" id="Form_number" name="Form_number" value={{userdata.Form_number}} readonly>
                </div>
                
                <label for="aname" class="form-label">Applicant Name*</label>
                <div class="form-group">
                    <input type="text" class="form-control mb-3" id="Applicant_name" name="Applicant_name" value= "{{userdata.Applicant_name}}">
                </div>
                <label for="dname" class="form-label">Deceased Name*</label>
                <div class="form-group">
                    <input type="text" class="form-control mb-3" id="Deceased_name" name="Deceased_name" value="{{userdata.Deceased_name}}"
                        placeholder="Enter Deceased Name">
                </div>
                <label for="dage" class="form-label">Deceased Age*</label>
                <div class="form-group">
                    <input type="text" class="form-control mb-3" id="Deceased_age" name="Deceased_age" value="{{userdata.Deceased_age}}"
                        placeholder="Enter Deceased Age">
                </div>
                <label for="gen" class="form-label">Gender*</label>
                <div class="form-group">
                    <select name="Gender" id="Gender" class="form-control mb-3">
                    <option value="Male">Male</option>
                    <option value="Female">Female</option>
                    </select>
                </div>
                <label for="cno" class="form-label">Phone Number*</label>
                <div class="form-group">
                    <input type="text" class="form-control mb-3" id="Contact_number" onkeypress="Contact_number1()" name="Contact_number" maxlength="10" value="{{userdata.Contact_number}}"
                     placeholder="Enter Phone Number"  readonly>
                </div>
                
                <label for="Address" class="form-label">Address*</label>
                <div class="form-group">
                    <input type="text" id="Address" name="Address" height="90" width="3" class="form-control mb-3" value="{{userdata.Address}}"
                        placeholder="Enter Address" >
                </div>
                <label for="daddress" class="form-label">Deceased Address*</label>
                <div class="form-group">
                    <input type="text" id="Deceased_address" name="Deceased_address" cols="90" rows="3" class="form-control" value="{{userdata.Deceased_address}}"
                        placeholder="Enter Deceased Address">
                </div>
                <label for="rel" class="form-label">Relationship*</label>
                <div class="form-group">
                    <input type="text" class="form-control mb-3" id="Relationship" name="Relationship" value="{{userdata.Relationship}}"
                        placeholder="Enter Relationship">
                </div>
                <label for="Cdeath" class="form-label">Cause Of Death*</label>
                <div class="form-group">
                    <input type="text" class="form-control mb-3" id="Cause_of_death" name="Cause_of_death" value="{{userdata.Cause_of_death}}"
                        placeholder="Enter Cause Of Death">
                </div>
                <label for="Date" class="form-label">Date</label>
                <div class="form-group">
                    <input type="text" class="form-control mb-3" id="Date" name="Date" value="{{dates}}"
                        placeholder="Enter Date">
                </div>
                <label for="dDate" class="form-label">Date Of Death</label>
                <div class="form-group">
                    <input type="text" class="form-control mb-3" id="Date_of_death" name="Date_of_death" value="{{dod}}"
                        placeholder="Enter Date Of Death">
                </div>
                <label for="tim" class="form-label">Time Of Death</label>
                <div class="form-group">
                    <input type="text" class="form-control mb-3" id="time_of_death" name="time_of_death" value="{{tod}}"
                        placeholder="Enter Time Of Death">
                </div>
                
                <label for="acard" class="form-label">Upload Aadhar card</label>
                <input type="file" class="form-control mb-3" id="id_Aadhar_card" name="Aadhar_card" value="{{userdata.Aadhar_card}}">

                <label for="dcard" class="form-label">Upload Death Certificate</label>
                <input type="file" class="form-control mb-3" id="id_Death_certificate" name="Death_certificate" value="{{userdata.Death_certificate}}">

                <label for="ocard" class="form-label">Upload Other File</label>
                <input type="file" class="form-control mb-3" id="id_Other_file" name="Other_file" value="{{userdata.Other_file}}">
                
                <label for="Amount" class="form-label">Amount*</label>
                <div class="form-group">
                    <input type="number" class="form-control mb-3" id="Amount" name="Amount" value="{{userdata.Amount}}"
                        placeholder="Enter Amount">
                </div>
                <button class="btn btn-dark d-grid mx-auto col-6 mt-4 mb-3 " type="submit">Update</button>
            
            </form>
            {% endfor %}
            
        </div>
    </div>
</div>
</div>



<script>  
    function Contact_number1(){          
     $('#Contact_number').keypress(function(e) {
         var a = [];
         var k = e.which;

         for (i = 48; i < 58; i++)
             a.push(i);

         if (!(a.indexOf(k)>=0))
             e.preventDefault();
     });
 }

 

</script>
{% endblock body %}

jamatulmsl/templates/export.html
{% extends 'base.html' %}
{% block body %}
<html>

<head>
    <title>UPDATE APPLICANT</title>
</head>
<style>
    h1 {
        text-align: center;
        color: rgb(255, 0, 0);
        font-size: 100px;
    }
    
    .container {
    width: 100%;
    padding-right: 30px;
    padding-left: 15px;
    margin-right: auto;
    margin-left: auto;
}
</style>

<div class="container">
    <div class="row pt-5 mb-3">
        <div class="text-center col-md-5"></div>
        <div class="col-md-12 mt-3 mb-3 ml-2 mr-2 my-auto border border-dark border-2 rounded-3">
            <h3 class="text-center mb-3 mt-3"><b>SELECT DATE RANGE FOR EXPORT DATA</h3></b>
            {% for message in messages %}
            <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
                {{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
            <form action="/exporttoexcel" method="post">{% csrf_token %}

                <label for="startDate" class="form-label">Start Date*</label>
                <div class="form-group">
                    <input type="Date" class="form-control mb-3" id="startDate" name="startDate"
                        placeholder="Enter Date" required>
                </div>
                <label for="endDate" class="form-label">End Date*</label>
                <div class="form-group">
                    <input type="Date" class="form-control mb-3" id="endDate" name="endDate" placeholder="Enter Date" required>
                </div>
                <button class="btn btn-dark d-grid mx-auto col-6 mt-4 mb-3" name="button" type="submit">Download CSV</button>
            </form>
        </div>
    </div>
</div>
        
</html>
{% endblock body %}

jamatulmsl/templates/registrationform.html
{% extends 'base.html' %}

<!-- changing title of page -->

{% block title %}
Registration Form
{% endblock title %}

{% block body %}

<!-- creating container for adding details -->
<style>
    .container {
        width: 100%;
        padding-right: 30px;
        padding-left: 15px;
        margin-right: auto;
        margin-left: auto;
    }
</style>
<div class="container">
    <div class="row pt-2 mb-3">
        <div class="text-center col-md-6"></div>
        <div class="col-md-12 mt-3 mb-3 ml-2 mr-2 my-auto border border-dark border-2 rounded-3">
            <h3 class="text-center mb-3 mt-3">FILL APPLICANT DETAILS</h3>

            {% for message in messages %}
            <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
                {{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}

            <!-- creating form for adding resume details -->

            <form action="/addResume" method="post" enctype="multipart/form-data">{% csrf_token %}
                <label for="userid" class="form-label">User ID*</label>
                <div class="form-group">
                    <input type="text" class="form-control mb-3" id="USERID" name="USERID" value="{{user.username}}"
                        placeholder="Enter  user id" required readonly>
                </div>
                <label for="fno" class="form-label">Form Number*</label>
                <div class="form-group">
                    <input type="text" class="form-control mb-3" id="Form_number" name="Form_number" value="{{context}}"
                        placeholder="Enter Form Number" required readonly>
                </div>
                <label for="aname" class="form-label">Applicant Name*</label>
                <div class="form-group">
                    <input type="text" class="form-control mb-3" id="Applicant_name" name="Applicant_name"
                        placeholder="Enter Applicant Name" required>
                </div>
                <label for="dname" class="form-label">Deceased Name*</label>
                <div class="form-group">
                    <input type="text" class="form-control mb-3" id="Deceased_name" name="Deceased_name"
                        placeholder="Enter Deceased Name" required>
                </div>
                <label for="dage" class="form-label">Deceased Age*</label>
                <div class="form-group">
                    <input type="text" class="form-control mb-3" id="Deceased_age" name="Deceased_age"
                        placeholder="Enter Deceased Age" required>
                </div>
                <label for="gen" class="form-label">Gender*</label>
                <div class="form-group">
                    <select name="Gender" id="Gender" class="form-control mb-3">
                        <option value="Male">Male</option>
                        <option value="Female">Female</option>
                    </select>
                </div>
                <label for="cno" class="form-label">Phone Number*</label>
                <div class="form-group">
                    <input type="text" class="form-control mb-3" id="Contact_number" onkeypress="Contact_number1()"
                        name="Contact_number" maxlength="10" placeholder="Enter Phone Number" required>
                </div>

                <label for="Address" class="form-label">Address*</label>
                <div class="form-group">
                    <textarea id="Address" name="Address" cols="90" rows="3" class="form-control"
                        placeholder="Enter Address" required></textarea>
                </div>
                <label for="daddress" class="form-label">Deceased Address*</label>
                <div class="form-group">
                    <textarea id="Deceased_address" name="Deceased_address" cols="90" rows="3" class="form-control"
                        placeholder="Enter Deceased Address" required></textarea>
                </div>
                <label for="rel" class="form-label">Relationship*</label>
                <div class="form-group">
                    <input type="text" class="form-control mb-3" id="Relationship" name="Relationship"
                        placeholder="Enter Relationship" required>
                </div>
                <label for="Cdeath" class="form-label">Cause Of Death*</label>
                <div class="form-group">
                    <input type="text" class="form-control mb-3" id="Cause_of_death" name="Cause_of_death"
                        placeholder="Enter Cause Of Death" required>
                </div>
                <label for="Date" class="form-label">Date</label>
                <div class="form-group">
                    <input type="Date" class="form-control mb-3" id="Date" name="Date" placeholder="Enter Date">
                </div>
                <label for="dDate" class="form-label">Date Of Death</label>
                <div class="form-group">
                    <input type="Date" class="form-control mb-3" id="Date_of_death" name="Date_of_death"
                        placeholder="Enter Date Of Death">
                </div>
                <label for="tim" class="form-label">Time Of Death</label>
                <div class="form-group">
                    <input type="Time" class="form-control mb-3" id="time_of_death" name="time_of_death"
                        placeholder="Enter Time Of Death">
                </div>

                <label for="acard" class="form-label">Upload Aadhar card</label>
                <input type="file" class="form-control mb-3" id="id_Aadhar_card" name="Aadhar_card">

                <label for="dcard" class="form-label">Upload Death Certificate</label>
                <input type="file" class="form-control mb-3" id="id_Death_certificate" name="Death_certificate">

                <label for="ocard" class="form-label">Upload Other File</label>
                <input type="file" class="form-control mb-3" id="id_Other_file" name="Other_file">

                <label for="Amount" class="form-label">Amount*</label>
                <div class="form-group">
                    <input type="number" class="form-control mb-3" id="Amount" name="Amount" placeholder="Enter Amount"
                        required>
                </div>
                <button class="btn btn-dark d-grid mx-auto col-6 mt-4 mb-3" type="submit">SUBMIT</button>
            </form>

        </div>
    </div>
</div>
</div>



<script>
    function Contact_number1() {
        $('#Contact_number').keypress(function (e) {
            var a = [];
            var k = e.which;

            for (i = 48; i < 58; i++)
                a.push(i);

            if (!(a.indexOf(k) >= 0))
                e.preventDefault();
        });
    }
</script>
{% endblock body %}